services:
  telegram-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram-bot-service
    ports:
      - 5432:5432
    volumes:
      - telegram-db-data:/var/lib/postgresql/data

volumes:
  telegram-db-data: