services:
  telegram-db:
    networks:
      - shared-net
    container_name: postgres-tg
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram-bot-service
    ports:
      - 5432:5432
    volumes:
      - telegram-db-data:/var/lib/postgresql/data\
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d telegram-bot-service" ]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    networks:
      - shared-net
    build: .
    command: ["/app/migrator", "up"]
    environment:
      - DSN=${DSN}
      - DIR=${DIR}
    depends_on:
      telegram-db:
        condition: service_healthy
    restart: on-failure

  bot:
    networks:
      - shared-net
    build: .
    command: ["/app/bot"]
    environment:
      - DB_DRIVER_NAME=${DB_DRIVER_NAME}
      - DSN=${DSN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GRPC_ADDRESS=${GRPC_ADDRESS}
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  shared-net:
    name: shared-services-net
    external: true

volumes:
  telegram-db-data: